package icons;

import com.intellij.openapi.util.IconLoader;
import consulo.ui.image.Image;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class TestngIcons {
  private static Image load(String path) {
    return IconLoader.getIcon(path, TestngIcons.class);
  }

  public static final Image TestNG = load("/resources/testNG.png"); // 16x16
}
